name: minify-version-publish-to-dist
on:
  push:
    paths:
      - 'vgauge.js'

jobs:

  publish:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.step2.outputs.version }}
    steps:
      - id: step1
        name: Checkout
        uses: actions/checkout@v4
        
      - id: step2
        name: Parse file, read version, check if exists in dist, if not write file and minified version to dist
        run: dotnet run --project .github/MinifyVersionPublishToFolder/MinifyVersionPublishToFolder.csproj vgauge.js dist

      - id: step3
        name: Add commit and push
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions

  release:
    runs-on: ubuntu-latest
    needs: publish
    steps:  
      - id: step1
        name: Checkout
        uses: actions/checkout@v4

      - id: step2
        name: Create release
        env:
          VERSION: ${{needs.publish.outputs.version}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            zip -r dist.zip ./dist/*
            gh release create "$VERSION" \
                --repo="$GITHUB_REPOSITORY" \
                --title="${VERSION}" \
                --generate-notes
            gh release upload "$VERSION" dist.zip
            echo "::notice file=dotnet.yml::Created release $VERSION"

  clean:
    runs-on: ubuntu-latest
    needs: [publish, release]
    steps: 
      - id: step1
        name: Checkout
        uses: actions/checkout@v4

      - id: step2
        name: Delete default assets
        env:
          VERSION: ${{needs.publish.outputs.version}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            gh release delete-asset "$VERSION" "${VERSION}.zip#Source code (zip)" -y
            gh release delete-asset "$VERSION" "${VERSION}.tar.gz#Source code (tar.gz)" -y
            echo "::notice file=dotnet.yml::Cleaned release $VERSION"
