name: minify-version-publish-to-dist
on:
  push:
    paths:
      - 'vgauge.js'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Parse file, read version, check if exists in dist, if not write file and minified version to dist
        run: |
             echo "minify version publish to dist" 
             dotnet run --project .github/MinifyVersionPublishToFolder/MinifyVersionPublishToFolder.csproj vgauge.js dist
             echo "test"
             echo $min_file_path
      - uses: actions/upload-artifact@v4
        with:
            name: min-file-path
            path: /home/runner/work/VGauge/VGauge/dist/vgauge-1.0.2.min.js
