name: minify-version-publish-to-dist
on:
  push:
    paths:
      - 'vgauge.js'

jobs:

  publish:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.step2.outputs.version }}
    steps:
      - id: step1
        name: Checkout
        uses: actions/checkout@v4
        
      - id: step2
        name: Parse file, read version, check if exists in dist, if not write file and minified version to dist
        run: dotnet run --project .github/MinifyVersionPublishToFolder/MinifyVersionPublishToFolder.csproj vgauge.js dist

      - id: step3
        name: Add commit and push
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions

  release:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Create release
        env:
          VERSION: ${{needs.publish.outputs.version}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
            echo ${{needs.publish.outputs.version}}
          # gh release create "$tag" \
          #     --repo="$GITHUB_REPOSITORY" \
          #     --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
          #     --generate-notes
